-- begin TRUONGHOC_THUTIENHOCPHI
alter table TRUONGHOC_THUTIENHOCPHI add constraint FK_TRUONGHOC_THUTIENHOCPHI_ON_DONVI foreign key (DONVI_ID) references TRUONGHOC_DONVI(ID)^
alter table TRUONGHOC_THUTIENHOCPHI add constraint FK_TRUONGHOC_THUTIENHOCPHI_ON_TENHOCSINH foreign key (TENHOCSINH_ID) references TRUONGHOC_HOCSINH(ID)^
create index IDX_TRUONGHOC_THUTIENHOCPHI_ON_DONVI on TRUONGHOC_THUTIENHOCPHI (DONVI_ID)^
create index IDX_TRUONGHOC_THUTIENHOCPHI_ON_TENHOCSINH on TRUONGHOC_THUTIENHOCPHI (TENHOCSINH_ID)^
-- end TRUONGHOC_THUTIENHOCPHI
-- begin TRUONGHOC_LUONGTHANG
alter table TRUONGHOC_LUONGTHANG add constraint FK_TRUONGHOC_LUONGTHANG_ON_DONVI foreign key (DONVI_ID) references TRUONGHOC_DONVI(ID)^
alter table TRUONGHOC_LUONGTHANG add constraint FK_TRUONGHOC_LUONGTHANG_ON_HOVATEN foreign key (HOVATEN_ID) references TRUONGHOC_GIAOVIEN(ID)^
create index IDX_TRUONGHOC_LUONGTHANG_ON_DONVI on TRUONGHOC_LUONGTHANG (DONVI_ID)^
create index IDX_TRUONGHOC_LUONGTHANG_ON_HOVATEN on TRUONGHOC_LUONGTHANG (HOVATEN_ID)^
-- end TRUONGHOC_LUONGTHANG
-- begin TRUONGHOC_THUCHI
alter table TRUONGHOC_THUCHI add constraint FK_TRUONGHOC_THUCHI_ON_DONVI foreign key (DONVI_ID) references TRUONGHOC_DONVI(ID)^
create index IDX_TRUONGHOC_THUCHI_ON_DONVI on TRUONGHOC_THUCHI (DONVI_ID)^
-- end TRUONGHOC_THUCHI
-- begin TRUONGHOC_HOCSINH
alter table TRUONGHOC_HOCSINH add constraint FK_TRUONGHOC_HOCSINH_ON_DONVI foreign key (DONVI_ID) references TRUONGHOC_DONVI(ID)^
alter table TRUONGHOC_HOCSINH add constraint FK_TRUONGHOC_HOCSINH_ON_NGAYSINHHOCSINH foreign key (NGAYSINHHOCSINH_ID) references TRUONGHOC_NAMSINH(ID)^
alter table TRUONGHOC_HOCSINH add constraint FK_TRUONGHOC_HOCSINH_ON_NOI_SINH_XA_PHUONG foreign key (NOI_SINH_XA_PHUONG_ID) references TRUONGHOC_XA_PHUONG(ID)^
alter table TRUONGHOC_HOCSINH add constraint FK_TRUONGHOC_HOCSINH_ON_NOI_SINH_QUAN_HUYEN foreign key (NOI_SINH_QUAN_HUYEN_ID) references TRUONGHOC_QUAN_HUYEN(ID)^
alter table TRUONGHOC_HOCSINH add constraint FK_TRUONGHOC_HOCSINH_ON_NOI_SINH_TINH_THANH foreign key (NOI_SINH_TINH_THANH_ID) references TRUONGHOC_TINH_THANH(ID)^
create index IDX_TRUONGHOC_HOCSINH_ON_DONVI on TRUONGHOC_HOCSINH (DONVI_ID)^
create index IDX_TRUONGHOC_HOCSINH_ON_NGAYSINHHOCSINH on TRUONGHOC_HOCSINH (NGAYSINHHOCSINH_ID)^
create index IDX_TRUONGHOC_HOCSINH_ON_NOI_SINH_XA_PHUONG on TRUONGHOC_HOCSINH (NOI_SINH_XA_PHUONG_ID)^
create index IDX_TRUONGHOC_HOCSINH_ON_NOI_SINH_QUAN_HUYEN on TRUONGHOC_HOCSINH (NOI_SINH_QUAN_HUYEN_ID)^
create index IDX_TRUONGHOC_HOCSINH_ON_NOI_SINH_TINH_THANH on TRUONGHOC_HOCSINH (NOI_SINH_TINH_THANH_ID)^
-- end TRUONGHOC_HOCSINH
-- begin TRUONGHOC_TENLOP
alter table TRUONGHOC_TENLOP add constraint FK_TRUONGHOC_TENLOP_ON_DOVI foreign key (DOVI_ID) references TRUONGHOC_DONVI(ID)^
alter table TRUONGHOC_TENLOP add constraint FK_TRUONGHOC_TENLOP_ON_GIAOVIENCN foreign key (GIAOVIENCN_ID) references TRUONGHOC_GIAOVIEN(ID)^
create index IDX_TRUONGHOC_TENLOP_ON_DOVI on TRUONGHOC_TENLOP (DOVI_ID)^
create index IDX_TRUONGHOC_TENLOP_ON_GIAOVIENCN on TRUONGHOC_TENLOP (GIAOVIENCN_ID)^
-- end TRUONGHOC_TENLOP
-- begin TRUONGHOC_DIEMDANH
alter table TRUONGHOC_DIEMDANH add constraint FK_TRUONGHOC_DIEMDANH_ON_GIAOVIENDD foreign key (GIAOVIENDD_ID) references TRUONGHOC_GIAOVIEN(ID)^
alter table TRUONGHOC_DIEMDANH add constraint FK_TRUONGHOC_DIEMDANH_ON_LOPDD foreign key (LOPDD_ID) references TRUONGHOC_TENLOP(ID)^
alter table TRUONGHOC_DIEMDANH add constraint FK_TRUONGHOC_DIEMDANH_ON_DONVIDD foreign key (DONVIDD_ID) references TRUONGHOC_DONVI(ID)^
alter table TRUONGHOC_DIEMDANH add constraint FK_TRUONGHOC_DIEMDANH_ON_HOTENHS foreign key (HOTENHS_ID) references TRUONGHOC_LOPHOC(ID)^
create index IDX_TRUONGHOC_DIEMDANH_ON_GIAOVIENDD on TRUONGHOC_DIEMDANH (GIAOVIENDD_ID)^
create index IDX_TRUONGHOC_DIEMDANH_ON_LOPDD on TRUONGHOC_DIEMDANH (LOPDD_ID)^
create index IDX_TRUONGHOC_DIEMDANH_ON_DONVIDD on TRUONGHOC_DIEMDANH (DONVIDD_ID)^
create index IDX_TRUONGHOC_DIEMDANH_ON_HOTENHS on TRUONGHOC_DIEMDANH (HOTENHS_ID)^
-- end TRUONGHOC_DIEMDANH
-- begin TRUONGHOC_CHAMCONGGV
alter table TRUONGHOC_CHAMCONGGV add constraint FK_TRUONGHOC_CHAMCONGGV_ON_HOTENGV foreign key (HOTENGV_ID) references TRUONGHOC_GIAOVIEN(ID)^
alter table TRUONGHOC_CHAMCONGGV add constraint FK_TRUONGHOC_CHAMCONGGV_ON_DONVIGV foreign key (DONVIGV_ID) references TRUONGHOC_DONVI(ID)^
create index IDX_TRUONGHOC_CHAMCONGGV_ON_HOTENGV on TRUONGHOC_CHAMCONGGV (HOTENGV_ID)^
create index IDX_TRUONGHOC_CHAMCONGGV_ON_DONVIGV on TRUONGHOC_CHAMCONGGV (DONVIGV_ID)^
-- end TRUONGHOC_CHAMCONGGV
-- begin TRUONGHOC_GIAOVIEN
alter table TRUONGHOC_GIAOVIEN add constraint FK_TRUONGHOC_GIAOVIEN_ON_DONVI foreign key (DONVI_ID) references TRUONGHOC_DONVI(ID)^
create index IDX_TRUONGHOC_GIAOVIEN_ON_DONVI on TRUONGHOC_GIAOVIEN (DONVI_ID)^
-- end TRUONGHOC_GIAOVIEN
-- begin TRUONGHOC_HOCPHI
alter table TRUONGHOC_HOCPHI add constraint FK_TRUONGHOC_HOCPHI_ON_DONVI foreign key (DONVI_ID) references TRUONGHOC_DONVI(ID)^
alter table TRUONGHOC_HOCPHI add constraint FK_TRUONGHOC_HOCPHI_ON_HOVATEN foreign key (HOVATEN_ID) references TRUONGHOC_HOCSINH(ID)^
create index IDX_TRUONGHOC_HOCPHI_ON_DONVI on TRUONGHOC_HOCPHI (DONVI_ID)^
create index IDX_TRUONGHOC_HOCPHI_ON_HOVATEN on TRUONGHOC_HOCPHI (HOVATEN_ID)^
-- end TRUONGHOC_HOCPHI
-- begin TRUONGHOC_LOPHOC
alter table TRUONGHOC_LOPHOC add constraint FK_TRUONGHOC_LOPHOC_ON_DONVI foreign key (DONVI_ID) references TRUONGHOC_DONVI(ID)^
alter table TRUONGHOC_LOPHOC add constraint FK_TRUONGHOC_LOPHOC_ON_GIAOVIENCN foreign key (GIAOVIENCN_ID) references TRUONGHOC_GIAOVIEN(ID)^
alter table TRUONGHOC_LOPHOC add constraint FK_TRUONGHOC_LOPHOC_ON_TENLOP foreign key (TENLOP_ID) references TRUONGHOC_TENLOP(ID)^
alter table TRUONGHOC_LOPHOC add constraint FK_TRUONGHOC_LOPHOC_ON_DSHOCSINH foreign key (DSHOCSINH_ID) references TRUONGHOC_HOCSINH(ID)^
create index IDX_TRUONGHOC_LOPHOC_ON_DONVI on TRUONGHOC_LOPHOC (DONVI_ID)^
create index IDX_TRUONGHOC_LOPHOC_ON_GIAOVIENCN on TRUONGHOC_LOPHOC (GIAOVIENCN_ID)^
create index IDX_TRUONGHOC_LOPHOC_ON_TENLOP on TRUONGHOC_LOPHOC (TENLOP_ID)^
create index IDX_TRUONGHOC_LOPHOC_ON_DSHOCSINH on TRUONGHOC_LOPHOC (DSHOCSINH_ID)^
-- end TRUONGHOC_LOPHOC
-- begin TRUONGHOC_CHITIETTHU
alter table TRUONGHOC_CHITIETTHU add constraint FK_TRUONGHOC_CHITIETTHU_ON_THUTIENHOCPHI foreign key (THUTIENHOCPHI_ID) references TRUONGHOC_THUTIENHOCPHI(ID)^
create index IDX_TRUONGHOC_CHITIETTHU_ON_THUTIENHOCPHI on TRUONGHOC_CHITIETTHU (THUTIENHOCPHI_ID)^
-- end TRUONGHOC_CHITIETTHU

-- begin SEC_USER
alter table SEC_USER add constraint FK_SEC_USER_ON_LOOCKUP_DONVI foreign key (LOOCKUP_DONVI_ID) references TRUONGHOC_DONVI(ID)^
create index IDX_SEC_USER_ON_LOOCKUP_DONVI on SEC_USER (LOOCKUP_DONVI_ID)^
alter table SEC_USER add constraint FK_SEC_USER_ON_GIAOVIEN foreign key (GIAOVIEN_ID) references TRUONGHOC_GIAOVIEN(ID)^
create index IDX_SEC_USER_ON_GIAOVIEN on SEC_USER (GIAOVIEN_ID)^
-- end SEC_USER
-- begin TRUONGHOC_XA_PHUONG
alter table TRUONGHOC_XA_PHUONG add constraint FK_TRUONGHOC_XA_PHUONG_ON_QUAN_HUYEN foreign key (QUAN_HUYEN_ID) references TRUONGHOC_QUAN_HUYEN(ID)^
alter table TRUONGHOC_XA_PHUONG add constraint FK_TRUONGHOC_XA_PHUONG_ON_TINH_THANH foreign key (TINH_THANH_ID) references TRUONGHOC_TINH_THANH(ID)^
create index IDX_TRUONGHOC_XA_PHUONG_ON_QUAN_HUYEN on TRUONGHOC_XA_PHUONG (QUAN_HUYEN_ID)^
create index IDX_TRUONGHOC_XA_PHUONG_ON_TINH_THANH on TRUONGHOC_XA_PHUONG (TINH_THANH_ID)^
-- end TRUONGHOC_XA_PHUONG
-- begin TRUONGHOC_QUAN_HUYEN
alter table TRUONGHOC_QUAN_HUYEN add constraint FK_TRUONGHOC_QUAN_HUYEN_ON_TINH_THANH foreign key (TINH_THANH_ID) references TRUONGHOC_TINH_THANH(ID)^
create index IDX_TRUONGHOC_QUAN_HUYEN_ON_TINH_THANH on TRUONGHOC_QUAN_HUYEN (TINH_THANH_ID)^
-- end TRUONGHOC_QUAN_HUYEN
