-- begin TRUONGHOC_LUONGTHANG
alter table TRUONGHOC_LUONGTHANG add constraint FK_TRUONGHOC_LUONGTHANG_ON_HOVATEN foreign key (HOVATEN_ID) references TRUONGHOC_GIAOVIEN(ID)^
create index IDX_TRUONGHOC_LUONGTHANG_ON_HOVATEN on TRUONGHOC_LUONGTHANG (HOVATEN_ID)^
-- end TRUONGHOC_LUONGTHANG
-- begin TRUONGHOC_HOCPHI
alter table TRUONGHOC_HOCPHI add constraint FK_TRUONGHOC_HOCPHI_ON_HOVATEN foreign key (HOVATEN_ID) references TRUONGHOC_HOCSINH(ID)^
create index IDX_TRUONGHOC_HOCPHI_ON_HOVATEN on TRUONGHOC_HOCPHI (HOVATEN_ID)^
-- end TRUONGHOC_HOCPHI
-- begin SEC_USER
alter table SEC_USER add constraint FK_SEC_USER_ON_HAIHAI foreign key (HAIHAI_ID) references TRUONGHOC_DONVI(ID)^
create index IDX_SEC_USER_ON_HAIHAI on SEC_USER (HAIHAI_ID)^
-- end SEC_USER
