alter table TRUONGHOC_HOCSINH add constraint FK_TRUONGHOC_HOCSINH_ON_LOPHOC foreign key (LOPHOC_ID) references TRUONGHOC_LOPHOC(ID);
create index IDX_TRUONGHOC_HOCSINH_ON_LOPHOC on TRUONGHOC_HOCSINH (LOPHOC_ID);
