alter table TRUONGHOC_THUCHI add constraint FK_TRUONGHOC_THUCHI_ON_DONVITAO_THUCHI foreign key (DONVITAO_THUCHI_ID) references TRUONGHOC_DONVI(ID);
create index IDX_TRUONGHOC_THUCHI_ON_DONVITAO_THUCHI on TRUONGHOC_THUCHI (DONVITAO_THUCHI_ID);
