alter table TRUONGHOC_TENLOP add constraint FK_TRUONGHOC_TENLOP_ON_GIAOVIENCN foreign key (GIAOVIENCN_ID) references TRUONGHOC_GIAOVIEN(ID);
create index IDX_TRUONGHOC_TENLOP_ON_GIAOVIENCN on TRUONGHOC_TENLOP (GIAOVIENCN_ID);
