exec sp_rename 'TRUONGHOC_DIEMDANH.HOTENHS_ID', 'HOTENHS_ID__U01676', 'COLUMN' ^
alter table TRUONGHOC_DIEMDANH drop constraint FK_TRUONGHOC_DIEMDANH_ON_HOTENHS ;
drop index IDX_TRUONGHOC_DIEMDANH_ON_HOTENHS on TRUONGHOC_DIEMDANH ;
