alter table TRUONGHOC_HOCSINH add constraint FK_TRUONGHOC_HOCSINH_ON_DIEMDANH foreign key (DIEMDANH_ID) references TRUONGHOC_DIEMDANH(ID);
create index IDX_TRUONGHOC_HOCSINH_ON_DIEMDANH on TRUONGHOC_HOCSINH (DIEMDANH_ID);
