alter table TRUONGHOC_DIEMDANH add constraint FK_TRUONGHOC_DIEMDANH_ON_NGUOITAODD foreign key (NGUOITAODD_ID) references TRUONGHOC_GIAOVIEN(ID);
create index IDX_TRUONGHOC_DIEMDANH_ON_NGUOITAODD on TRUONGHOC_DIEMDANH (NGUOITAODD_ID);
