exec sp_rename 'TRUONGHOC_THUTIENHOCPHI.DONGIA', 'DONGIA__U49331', 'COLUMN' ^
exec sp_rename 'TRUONGHOC_THUTIENHOCPHI.SOLUONG', 'SOLUONG__U65190', 'COLUMN' ^
exec sp_rename 'TRUONGHOC_THUTIENHOCPHI.TENPHI', 'TENPHI__U43931', 'COLUMN' ^
