exec sp_rename 'TRUONGHOC_THUCHI.DONVITAO_THUCHI', 'DONVITAO_THUCHI__U87401', 'COLUMN' ^
exec sp_rename 'TRUONGHOC_THUCHI.USERTAO_THUCHI', 'USERTAO_THUCHI__U48080', 'COLUMN' ^
alter table TRUONGHOC_THUCHI add USERTAO_THUCHI_ID uniqueidentifier ;
alter table TRUONGHOC_THUCHI add DONVITAO_THUCHI_ID uniqueidentifier ;
