alter table TRUONGHOC_LOPHOC add constraint FK_TRUONGHOC_LOPHOC_ON_GIAOVIENCN foreign key (GIAOVIENCN_ID) references TRUONGHOC_TENLOP(ID);
create index IDX_TRUONGHOC_LOPHOC_ON_GIAOVIENCN on TRUONGHOC_LOPHOC (GIAOVIENCN_ID);
