alter table TRUONGHOC_HOCPHI add constraint FK_TRUONGHOC_HOCPHI_ON_NAMSINH foreign key (NAMSINH_ID) references TRUONGHOC_HOCSINH(ID);
create index IDX_TRUONGHOC_HOCPHI_ON_NAMSINH on TRUONGHOC_HOCPHI (NAMSINH_ID);
