exec sp_rename 'TRUONGHOC_HOCPHI.DOVITAO_HOCPHI', 'DOVITAO_HOCPHI__U06237', 'COLUMN' ^
exec sp_rename 'TRUONGHOC_HOCPHI.USERTAO_HOCPHI', 'USERTAO_HOCPHI__U31760', 'COLUMN' ^
alter table TRUONGHOC_HOCPHI add DOVITAO_HOCPHI_ID uniqueidentifier ;
alter table TRUONGHOC_HOCPHI add USERTAO_HOCPHI_ID uniqueidentifier ;
