exec sp_rename 'TRUONGHOC_HOCSINH.DONVITAO_HOCSINH', 'DONVITAO_HOCSINH__U09349', 'COLUMN' ^
exec sp_rename 'TRUONGHOC_HOCSINH.USERTAO_HOCSINH', 'USERTAO_HOCSINH__U01034', 'COLUMN' ^
alter table TRUONGHOC_HOCSINH add DONVITAO_HOCSINH_ID uniqueidentifier ;
alter table TRUONGHOC_HOCSINH add USERTAO_HOCSINH_ID uniqueidentifier ;
