exec sp_rename 'TRUONGHOC_GIAOVIEN.DONVITAO_GIAOVIEN_ID', 'DONVITAO_GIAOVIEN_ID__U07459', 'COLUMN' ^
alter table TRUONGHOC_GIAOVIEN drop constraint FK_TRUONGHOC_GIAOVIEN_ON_DONVITAO_GIAOVIEN ;
drop index IDX_TRUONGHOC_GIAOVIEN_ON_DONVITAO_GIAOVIEN on TRUONGHOC_GIAOVIEN ;
alter table TRUONGHOC_GIAOVIEN add DONVITAO_GIAOVIEN nvarchar(255) ;
