exec sp_rename 'TRUONGHOC_HOCSINH.LOPHOC_ID', 'LOPHOC_ID__U01782', 'COLUMN' ^
alter table TRUONGHOC_HOCSINH drop constraint FK_TRUONGHOC_HOCSINH_ON_LOPHOC ;
drop index IDX_TRUONGHOC_HOCSINH_ON_LOPHOC on TRUONGHOC_HOCSINH ;
