alter table TRUONGHOC_THUCHI add constraint FK_TRUONGHOC_THUCHI_ON_USERTAO_THUCHI foreign key (USERTAO_THUCHI_ID) references TRUONGHOC_GIAOVIEN(ID);
create index IDX_TRUONGHOC_THUCHI_ON_USERTAO_THUCHI on TRUONGHOC_THUCHI (USERTAO_THUCHI_ID);
