exec sp_rename 'TRUONGHOC_THUTIENHOCPHI.DONVITAO_THUTIENHOCPHI', 'DONVITAO_THUTIENHOCPHI__U75682', 'COLUMN' ^
exec sp_rename 'TRUONGHOC_THUTIENHOCPHI.USERTAO_THUTIENHOCPHI', 'USERTAO_THUTIENHOCPHI__U47797', 'COLUMN' ^
alter table TRUONGHOC_THUTIENHOCPHI add USERTAO_THUTIENHOCPHI_ID uniqueidentifier ;
alter table TRUONGHOC_THUTIENHOCPHI add DONVITAO_THUTIENHOCPHI_ID uniqueidentifier ;
