create table TRUONGHOC_LUONGTHANG (
    ID uniqueidentifier,
    VERSION integer not null,
    CREATE_TS datetime2,
    CREATED_BY nvarchar(50),
    UPDATE_TS datetime2,
    UPDATED_BY nvarchar(50),
    DELETE_TS datetime2,
    DELETED_BY nvarchar(50),
    --
    USERTAO_LUONGTHANG nvarchar(255),
    DONVITAO_LUONGTHANG nvarchar(255),
    HOVATEN_ID uniqueidentifier not null,
    NGAYNHAN datetime2,
    HANNHANLUONG datetime2,
    LUONGCOBAN bigint,
    BUOILAM decimal(19, 2),
    CANGOAI integer,
    CASANG integer,
    THUCLINH bigint,
    DAYTHEM bigint,
    TROCAP bigint,
    TRACHNHIEM bigint,
    CHUYENCAN bigint,
    THUONG bigint,
    TONGLINH bigint,
    HINHTHUCTHANHTOAN nvarchar(255),
    TINHTRANGNHANLUONG nvarchar(255),
    --
    primary key nonclustered (ID)
);