exec sp_rename 'TRUONGHOC_THUTIENHOCPHI.TENHOCSINH_ID', 'TENHOCSINH_ID__U95976', 'COLUMN' ^
alter table TRUONGHOC_THUTIENHOCPHI drop constraint FK_TRUONGHOC_THUTIENHOCPHI_ON_TENHOCSINH ;
drop index IDX_TRUONGHOC_THUTIENHOCPHI_ON_TENHOCSINH on TRUONGHOC_THUTIENHOCPHI ;
alter table TRUONGHOC_THUTIENHOCPHI add TENHOCSINH_ID uniqueidentifier ;
