exec sp_rename 'TRUONGHOC_HOCPHI.NAMSINH_ID', 'NAMSINH_ID__U19902', 'COLUMN' ^
alter table TRUONGHOC_HOCPHI drop constraint FK_TRUONGHOC_HOCPHI_ON_NAMSINH ;
drop index IDX_TRUONGHOC_HOCPHI_ON_NAMSINH on TRUONGHOC_HOCPHI ;
