alter table TRUONGHOC_LOPHOC add constraint FK_TRUONGHOC_LOPHOC_ON_TENLOP foreign key (TENLOP_ID) references TRUONGHOC_TENLOP(ID);
create index IDX_TRUONGHOC_LOPHOC_ON_TENLOP on TRUONGHOC_LOPHOC (TENLOP_ID);
