-- begin TRUONGHOC_THUTIENHOCPHI
alter table TRUONGHOC_THUTIENHOCPHI add constraint FK_TRUONGHOC_THUTIENHOCPHI_ON_TENHOCSINH foreign key (TENHOCSINH_ID) references TRUONGHOC_HOCSINH(ID)^
create index IDX_TRUONGHOC_THUTIENHOCPHI_ON_TENHOCSINH on TRUONGHOC_THUTIENHOCPHI (TENHOCSINH_ID)^
-- end TRUONGHOC_THUTIENHOCPHI
-- begin TRUONGHOC_LUONGTHANG
alter table TRUONGHOC_LUONGTHANG add constraint FK_TRUONGHOC_LUONGTHANG_ON_HOVATEN foreign key (HOVATEN_ID) references TRUONGHOC_GIAOVIEN(ID)^
create index IDX_TRUONGHOC_LUONGTHANG_ON_HOVATEN on TRUONGHOC_LUONGTHANG (HOVATEN_ID)^
-- end TRUONGHOC_LUONGTHANG

-- begin TRUONGHOC_CHAMCONGGV
alter table TRUONGHOC_CHAMCONGGV add constraint FK_TRUONGHOC_CHAMCONGGV_ON_HOTENGV foreign key (HOTENGV_ID) references TRUONGHOC_GIAOVIEN(ID)^
create index IDX_TRUONGHOC_CHAMCONGGV_ON_HOTENGV on TRUONGHOC_CHAMCONGGV (HOTENGV_ID)^
-- end TRUONGHOC_CHAMCONGGV
-- begin TRUONGHOC_HOCPHI
alter table TRUONGHOC_HOCPHI add constraint FK_TRUONGHOC_HOCPHI_ON_HOVATEN foreign key (HOVATEN_ID) references TRUONGHOC_HOCSINH(ID)^
create index IDX_TRUONGHOC_HOCPHI_ON_HOVATEN on TRUONGHOC_HOCPHI (HOVATEN_ID)^
-- end TRUONGHOC_HOCPHI
-- begin SEC_USER
alter table SEC_USER add constraint FK_SEC_USER_ON_LOOCKUP_DONVI foreign key (LOOCKUP_DONVI_ID) references TRUONGHOC_DONVI(ID)^
create index IDX_SEC_USER_ON_LOOCKUP_DONVI on SEC_USER (LOOCKUP_DONVI_ID)^
alter table SEC_USER add constraint FK_SEC_USER_ON_GIAOVIEN foreign key (GIAOVIEN_ID) references TRUONGHOC_GIAOVIEN(ID)^
create index IDX_SEC_USER_ON_GIAOVIEN on SEC_USER (GIAOVIEN_ID)^
-- end SEC_USER
-- begin TRUONGHOC_CHITIETTHU
alter table TRUONGHOC_CHITIETTHU add constraint FK_TRUONGHOC_CHITIETTHU_ON_THUTIENHOCPHI foreign key (THUTIENHOCPHI_ID) references TRUONGHOC_THUTIENHOCPHI(ID)^
create index IDX_TRUONGHOC_CHITIETTHU_ON_THUTIENHOCPHI on TRUONGHOC_CHITIETTHU (THUTIENHOCPHI_ID)^
-- end TRUONGHOC_CHITIETTHU
-- begin TRUONGHOC_TENLOP
alter table TRUONGHOC_TENLOP add constraint FK_TRUONGHOC_TENLOP_ON_GIAOVIENCN foreign key (GIAOVIENCN_ID) references TRUONGHOC_GIAOVIEN(ID)^
create index IDX_TRUONGHOC_TENLOP_ON_GIAOVIENCN on TRUONGHOC_TENLOP (GIAOVIENCN_ID)^
-- end TRUONGHOC_TENLOP
-- begin TRUONGHOC_HOCSINH
alter table TRUONGHOC_HOCSINH add constraint FK_TRUONGHOC_HOCSINH_ON_LOPHOC foreign key (LOPHOC_ID) references TRUONGHOC_LOPHOC(ID)^
alter table TRUONGHOC_HOCSINH add constraint FK_TRUONGHOC_HOCSINH_ON_DIEMDANH foreign key (DIEMDANH_ID) references TRUONGHOC_DIEMDANH(ID)^
create index IDX_TRUONGHOC_HOCSINH_ON_LOPHOC on TRUONGHOC_HOCSINH (LOPHOC_ID)^
create index IDX_TRUONGHOC_HOCSINH_ON_DIEMDANH on TRUONGHOC_HOCSINH (DIEMDANH_ID)^
-- end TRUONGHOC_HOCSINH
