alter table TRUONGHOC_LOPHOC add constraint FK_TRUONGHOC_LOPHOC_ON_THANG foreign key (THANG_ID) references TRUONGHOC_TENLOP(ID);
create index IDX_TRUONGHOC_LOPHOC_ON_THANG on TRUONGHOC_LOPHOC (THANG_ID);
