alter table TRUONGHOC_XA_PHUONG add constraint FK_TRUONGHOC_XA_PHUONG_ON_QUAN_HUYEN foreign key (QUAN_HUYEN_ID) references TRUONGHOC_QUAN_HUYEN(ID);
alter table TRUONGHOC_XA_PHUONG add constraint FK_TRUONGHOC_XA_PHUONG_ON_TINH_THANH foreign key (TINH_THANH_ID) references TRUONGHOC_TINH_THANH(ID);
create index IDX_TRUONGHOC_XA_PHUONG_ON_QUAN_HUYEN on TRUONGHOC_XA_PHUONG (QUAN_HUYEN_ID);
create index IDX_TRUONGHOC_XA_PHUONG_ON_TINH_THANH on TRUONGHOC_XA_PHUONG (TINH_THANH_ID);
