alter table TRUONGHOC_CHAMCONGGV add constraint FK_TRUONGHOC_CHAMCONGGV_ON_TIEN_BUOI foreign key (TIEN_BUOI_ID) references TRUONGHOC_TIENLUONGTHEO_CA(ID);
create index IDX_TRUONGHOC_CHAMCONGGV_ON_TIEN_BUOI on TRUONGHOC_CHAMCONGGV (TIEN_BUOI_ID);
