exec sp_rename 'TRUONGHOC_HOCPHI.USERTAO_HOCPHI_ID', 'USERTAO_HOCPHI_ID__U86148', 'COLUMN' ^
alter table TRUONGHOC_HOCPHI drop constraint FK_TRUONGHOC_HOCPHI_ON_USERTAO_HOCPHI ;
drop index IDX_TRUONGHOC_HOCPHI_ON_USERTAO_HOCPHI on TRUONGHOC_HOCPHI ;
