exec sp_rename 'TRUONGHOC_CHAMCONGGV.TIEN_BUOI_ID', 'TIEN_BUOI_ID__U48371', 'COLUMN' ^
drop index IDX_TRUONGHOC_CHAMCONGGV_ON_TIEN_BUOI on TRUONGHOC_CHAMCONGGV ;
alter table TRUONGHOC_CHAMCONGGV add TIEN_BUOI integer ;
