exec sp_rename 'TRUONGHOC_DIEMDANH.LOPDD_ID', 'LOPDD_ID__U36985', 'COLUMN' ^
alter table TRUONGHOC_DIEMDANH drop constraint FK_TRUONGHOC_DIEMDANH_ON_LOPDD ;
drop index IDX_TRUONGHOC_DIEMDANH_ON_LOPDD on TRUONGHOC_DIEMDANH ;
alter table TRUONGHOC_DIEMDANH add LOPDD_ID uniqueidentifier ;
