alter table TRUONGHOC_HOCPHI add constraint FK_TRUONGHOC_HOCPHI_ON_USERTAO_HOCPHI foreign key (USERTAO_HOCPHI_ID) references TRUONGHOC_GIAOVIEN(ID);
alter table TRUONGHOC_HOCPHI add constraint FK_TRUONGHOC_HOCPHI_ON_DOVITAO_HOCPHI foreign key (DOVITAO_HOCPHI_ID) references TRUONGHOC_DONVI(ID);
alter table TRUONGHOC_HOCPHI add constraint FK_TRUONGHOC_HOCPHI_ON_HOVATEN foreign key (HOVATEN_ID) references TRUONGHOC_HOCSINH(ID);
create index IDX_TRUONGHOC_HOCPHI_ON_USERTAO_HOCPHI on TRUONGHOC_HOCPHI (USERTAO_HOCPHI_ID);
create index IDX_TRUONGHOC_HOCPHI_ON_DOVITAO_HOCPHI on TRUONGHOC_HOCPHI (DOVITAO_HOCPHI_ID);
create index IDX_TRUONGHOC_HOCPHI_ON_HOVATEN on TRUONGHOC_HOCPHI (HOVATEN_ID);
