alter table TRUONGHOC_LUONGTHANG add constraint FK_TRUONGHOC_LUONGTHANG_ON_TIEN_BH foreign key (TIEN_BH_ID) references TRUONGHOC_GIAOVIEN(ID);
create index IDX_TRUONGHOC_LUONGTHANG_ON_TIEN_BH on TRUONGHOC_LUONGTHANG (TIEN_BH_ID);
