exec sp_rename 'TRUONGHOC_THUCHI.USERTAO_THUCHI_ID', 'USERTAO_THUCHI_ID__U51392', 'COLUMN' ^
alter table TRUONGHOC_THUCHI drop constraint FK_TRUONGHOC_THUCHI_ON_USERTAO_THUCHI ;
drop index IDX_TRUONGHOC_THUCHI_ON_USERTAO_THUCHI on TRUONGHOC_THUCHI ;
