alter table TRUONGHOC_QUAN_HUYEN add constraint FK_TRUONGHOC_QUAN_HUYEN_ON_TINH_THANH foreign key (TINH_THANH_ID) references TRUONGHOC_TINH_THANH(ID);
create index IDX_TRUONGHOC_QUAN_HUYEN_ON_TINH_THANH on TRUONGHOC_QUAN_HUYEN (TINH_THANH_ID);
