alter table TRUONGHOC_XA_PHUONG add constraint FK_TRUONGHOC_XA_PHUONG_ON_QUAN_HUYEN foreign key (QUAN_HUYEN_ID) references TRUONGHOC_QUAN_HUYEN(ID);
create index IDX_TRUONGHOC_XA_PHUONG_ON_QUAN_HUYEN on TRUONGHOC_XA_PHUONG (QUAN_HUYEN_ID);
