alter table TRUONGHOC_THUTIENHOCPHI add constraint FK_TRUONGHOC_THUTIENHOCPHI_ON_DONVI foreign key (DONVI_ID) references TRUONGHOC_DONVI(ID);
create index IDX_TRUONGHOC_THUTIENHOCPHI_ON_DONVI on TRUONGHOC_THUTIENHOCPHI (DONVI_ID);
