alter table TRUONGHOC_GIAOVIEN add constraint FK_TRUONGHOC_GIAOVIEN_ON_DONVI foreign key (DONVI_ID) references TRUONGHOC_DONVI(ID);
create index IDX_TRUONGHOC_GIAOVIEN_ON_DONVI on TRUONGHOC_GIAOVIEN (DONVI_ID);
