alter table TRUONGHOC_LOPHOC add constraint FK_TRUONGHOC_LOPHOC_ON_DSHOCSINH foreign key (DSHOCSINH_ID) references TRUONGHOC_HOCSINH(ID);
create index IDX_TRUONGHOC_LOPHOC_ON_DSHOCSINH on TRUONGHOC_LOPHOC (DSHOCSINH_ID);
