alter table TRUONGHOC_HOCSINH add constraint FK_TRUONGHOC_HOCSINH_ON_DONVI foreign key (DONVI_ID) references TRUONGHOC_DONVI(ID);
create index IDX_TRUONGHOC_HOCSINH_ON_DONVI on TRUONGHOC_HOCSINH (DONVI_ID);
