alter table TRUONGHOC_LUONGTHANG add constraint FK_TRUONGHOC_LUONGTHANG_ON_DONVI foreign key (DONVI_ID) references TRUONGHOC_DONVI(ID);
create index IDX_TRUONGHOC_LUONGTHANG_ON_DONVI on TRUONGHOC_LUONGTHANG (DONVI_ID);
